### ISSUE TITLE
The info I was getting from uniswap was a mainnet pool despite being connected to Ropsten in my metamask. Hm. How do I find the pool for WETH-USDC on Ropsten?

### ISSUE THREAD

**Issue by leslinice** [Cottand/refereneceWacc4jvm#1]
The info I was getting from uniswap was a mainnet pool despite being connected to Ropsten in my metamask. Hm. How do I find the pool for WETH-USDC on Ropsten?

__Originally posted by @Developer5600 in https://github.com/centrehq/centre-tokens/issues/348#issuecomment-1092295135__

**Comment by cottand** [comment]
@leslinice are you sure this is the right repo? This project is not even crypto-related.

Closing for now
